default: &default
  adapter: postgresql
  encoding: utf8  
  pool: 5
  
development:
  <<: *default
  database: bowling_02_01_2019
  pool: 5
  username: davidmao
  password: cataratas
  host: localhost

# development: #postgresql-contoured-38648
#   <<: *default
#   database: d58qhdq47a3g31
#   pool: 5
#   username: mfomydlgqfwzin
#   password: 672b68a6417ee5131cdb99e008533183d272743025ba0cc025dfe6d359681263
#   host:     ec2-107-20-237-78.compute-1.amazonaws.com
#   sslmode:  require

# production: # bd de produccion en heroku dev 9$
#   <<: *default
#   database: d4r16b69o0a1oe
#   pool: 5
#   username: rrxmcghpgftifx
#   password: 78bbee3095e8604d409de92575f2428c79b254520636bd31a28f342f458753ce
#   host:     ec2-54-227-243-210.compute-1.amazonaws.com
#   sslmode:  require
  
#production:
#  <<: *default
#  database: d2lq33fke391a4
#  pool: 5
#  username: blebzysikmxjzy
#  password: 059fa686693f838e25f04ccd2f7624ece0711c65624f77acfa9d4c03d5b51053
#  host:     ec2-54-163-228-190.compute-1.amazonaws.com
#  sslmode:  require  
